dependencies:
- python=3.8
- pip
- pip:
  - IPython
  - ipykernel
  - tensorflow
  - numpy
  - pandas
  - matplotlib
  - scipy
  - fenics
  - fenics-ffcx
  - fenics-basix
  - pybind11
  - mpi4py
  - petsc4py
  - pyvista
